### ISSUE TITLE
Missing taint sinks for LDAP Injection

### ISSUE THREAD

**Issue by h3xstream** [h3xstream/find-sec-bugs#105]
Add coverage for the method search for DirContext
 - [DirContext.lookup()](http://docs.oracle.com/javase/7/docs/api/javax/naming/Context.html#lookup(javax.naming.Name))

Thanks to @mcwww for the information

**Comment by formanek** [comment]
It seems to be already included in ``JndiLdapInjectionSource``.

**Comment by h3xstream** [comment]
@formanek My mistake. The missing API was actually lookup.
Ref: https://www.owasp.org/index.php?title=OWASP_Backend_Security_Project_Java_Security_Programming&setlang=es#Examples_of_codes_vulnerable_to_LDAP_Injection

**Comment by h3xstream** [comment]
I will not added any new signature until the refactoring on taint detector is completed. #96
