### ISSUE TITLE
Add taint sinks for XPath injection

### ISSUE THREAD

**Issue by formanek** [h3xstream/find-sec-bugs#108]
Not all methods from ``org.apache.xpath.XPathAPI`` are included and there are more APIs to add.

**Comment by formanek** [comment]
There is also a bug in ``XPathInjectionJavaxDetector`` - bad argument in method ``evaluate`` is checked (0 instead of 1). Plus the other 3 methods with different signatures are not checked at all.

**Comment by h3xstream** [comment]
Consider fixed : https://github.com/formanek/find-sec-bugs/commit/5eb668675314bd2bd3e48f71167bb08a0fd4a941#diff-e7af01b3ebefa5f1b6ed5b5c44483905R1
