### ISSUE TITLE
Path traversal false positives

### ISSUE THREAD

**Issue by formanek** [h3xstream/find-sec-bugs#113]
There are two bugs in ``PathTraversalDetector``:

1. ``new RandomAccessFile("safe", "r")`` is reported, because access mode is checked (why?) for variable string and the condition is negated (typing error?), so a bug is shown for constants in the second argument. I think access mode should not be checked, since ``new RandomAccessFile("safe", tainted)`` is not very dangerous

2. ``new FileWriter("safe")`` is reported, because the checked argument is the same as for the 2-argument constructor, so the instance is checked (which is definitely not a constant string) and every ``FileWriter`` 1-argument constructor call is reported.

**Comment by h3xstream** [comment]
Nice catch.
