### ISSUE TITLE
How can I mark / exclude false positives?

### ISSUE THREAD

**Issue by DP4711** [h3xstream/find-sec-bugs#116]
Hi,

just a quick question. How can I mark (or exclude) false positives so that they aren't shown as an issue anymore?

E.g. 
`File file = new File(path);`

shows a possible PATH_TRAVERSAL_IN vulnerability. If I know that the path traversal can't happen I would like to exclude it. But using @SuppressFBWarnings doesn't work. The issue is still reported
```
@SuppressFBWarnings("PATH_TRAVERSAL_IN")
File file = new File(path);
```

**Comment by formanek** [comment]
@DP4711 Hi, this is the matter of FindBugs (not this plugin), but try moving the annotation to the method level. I prefer marking false positives externally.

**Comment by DP4711** [comment]
Ok. Thanks
