### ISSUE TITLE
IntelliJ findsecbugs plugin fails with unable to load descriptor file error

### ISSUE THREAD

**Issue by gpacersw** [h3xstream/find-sec-bugs#118]
Upon review of the findsecbugs-plugin-1.4.3.jar contents it does not contain a plugin.xml file in the META-INF directory.  I am using IntelliJ 14.1.5.  In looking at QAPlug - Findbugs for example, they have a plugin.xml file that starts with:

<idea-plugin version="2" url="http://qaplug.com">
    <name>QAPlug - FindBugs</name>
    <description>FindBugs module for QAPlug - an Intellij IDEA plugin to manage code quality which integrates tools such as PMD, Checkstyle and Findbugs. </description>
    <version>1.3.6</version>
    <vendor url="http://www.soldevelo.com" email="support@qaplug.com" logo="/com/soldevelo/qaplug/resources/icons/soldevelo_icon.png">SolDevelo</vendor>
    <idea-version since-build="133.193"/>

..

**Comment by h3xstream** [comment]
The `findbugs.xml` and `messages.xml`have always been in the root of the plugin.jar

Do you know what version FindBugs QAPlug is using? I am assuming it use the same API as IntelliJ and Eclipse plugins does.

**Comment by h3xstream** [comment]
The issue is not complete enough to allow any investigation.
