### ISSUE TITLE
Description for weak digest need an update

### ISSUE THREAD

**Issue by h3xstream** [h3xstream/find-sec-bugs#119]
The description are outdated.
http://h3xstream.github.io/find-sec-bugs/bugs.htm#WEAK_MESSAGE_DIGEST

The description was valid in 2012 but not now. SHA-1 should not be mentions. Also link to relevant article on the status of SHA-1.

**Comment by formanek** [comment]
I had the same idea. I also think that SHA-1 should be reported with higher priority (maybe with medium and raise priority of MD2 and MD5 to high). I've been modifying the `messages.xml` recently, please wait for my pull request until changing it to prevent merge conflicts.

**Comment by h3xstream** [comment]
Preview : http://h3xstream.github.io/find-sec-bugs/bugs.htm#WEAK_MESSAGE_DIGEST_SHA1
