### ISSUE TITLE
Support java 8 - upgrade to findbugs 3.0.0 or higher.

### ISSUE THREAD

**Issue by dbaxa** [h3xstream/find-sec-bugs#37]
Currently several find-sec-bugs detectors do not work with the findbugs 3.0.0, the tests fail, this means using find-sec-bugs under java 8 does not work properly.

**Comment by h3xstream** [comment]
Yup, I only saw the details of FindBugs 3.0 recently. http://comments.gmane.org/gmane.comp.java.findbugs.announce/62

Migration of BCEL to ASM will be require. Most likely modify the test framework.

**Comment by h3xstream** [comment]
In 5246e6a1506f8378b6c7fe8925616054295ae8dd, the travis-ci configuration was upgrade to Java 8. The build worked locally and [now on the CI environnement](https://travis-ci.org/h3xstream/find-sec-bugs/builds/54110990).

The change was easier than expected FindBugs seems to be backward compatible.

@dbaxa Can you do a test with your projects?

**Comment by dbaxa** [comment]
@h3xstream sure :-)

**Comment by dbaxa** [comment]
It seems to work fine with our projects.
