### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by kitenco** [h3xstream/find-sec-bugs#41]
Hi there,

I am using FindSecBugs for a while now, its very cool and helpful.
But as there are now more than 60 bug pattern, It would be nice to have release notes,
to see which patterns are new since v1.4.0

**Comment by h3xstream** [comment]
I will try to generated the list of enhancement made for the release.
I made effort to create issue for each new feature. It should help a bit.

**Comment by h3xstream** [comment]
https://github.com/h3xstream/find-sec-bugs/blob/master/CHANGELOG.md

Let me know if you have suggestion on what to highlight.
For the moment, this log is auto-generated.

**Comment by h3xstream** [comment]
GitHub has a section for the release notes. I think I will remove the CHANGELOG.md file.
https://github.com/h3xstream/find-sec-bugs/releases

I will not add release note to version prior <1.3.1. But, I will create similar summary for future releases.
