### ISSUE TITLE
XXE - reader False Positive

### ISSUE THREAD

**Issue by kjlubick** [h3xstream/find-sec-bugs#47]
I came across XXE_XMLREADER and used the recommended solution from http://h3xstream.github.io/find-sec-bugs/bugs.htm, but the bugs persist in my Eclipse Luna IDE.

I made two methods with exactly that recommended code, and they still show up as bugs.

![image](https://cloud.githubusercontent.com/assets/6819944/7332998/1be597f6-eb2b-11e4-96dd-53045b355d85.png)

![image](https://cloud.githubusercontent.com/assets/6819944/7333001/2bd36bfc-eb2b-11e4-8780-23f3c72c9236.png)

**Comment by h3xstream** [comment]
XMLReader was the only api with no false positive test... my bad. :)
It was assume that setFeature was the same as DocumentBuilder and SAXParser..

The fix will be included in the next release.
