### ISSUE TITLE
XXE Bug Patterns update

### ISSUE THREAD

**Issue by aabashkin** [h3xstream/find-sec-bugs#54]
Hello,

I'd like to submit a pattern update for XXE bugs. This provides a way to disable external entities without completely restricting DOCTYPE

```
		DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
		dbf.setFeature("http://xml.org/sax/features/external-general-entities", Boolean.FALSE);
```

```
		XMLReader reader = XMLReaderFactory.createXMLReader();
		
		GenericInputParserHandler handler = new GenericInputParserHandler();
		reader.setFeature("http://xml.org/sax/features/external-general-entities", Boolean.FALSE);
		reader.setContentHandler(handler);
```

**Comment by h3xstream** [comment]
@aabashkin 
Find-Security-Bugs supports many solutions to mitigate XXE.

The following is also supported.

    DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
    dbf.setFeature("http://xml.org/sax/features/external-general-entities",true);
    dbf.setFeature("http://xml.org/sax/features/external-parameter-entities",true);
    dbf.setXIncludeAware(false);
    dbf.setExpandEntityReferences(false);

The complete list of alternative is not listed in the description for simplicity. Explaining that "http://xml.org/sax/features/external-general-entities" mitigate partially file ex-filtration but still make the application vulnerable to Entities Expension can easily bring confusion.

The list of "totally" safe implementation are listed here : 
https://github.com/h3xstream/find-sec-bugs/blob/master/plugin/src/test/java/testcode/xxe/DocumentBuilderSafeProperty.java#L68

Let me know if you think it is still false positive/annoyance..

I'm not familiar with `GenericInputParserHandler`. Is it a proprietary api?

**Comment by cschneider4711** [comment]
Hallo,

Please also keep in mind that external parameter entities (not only external general entities) should also be disabled to mitigate XXE. Aside from that, even just resolving DTDs could be used to facilitate Server-Side Request Forgery attacks (SSRF). So just disabling external general entities would not be enough. 

Best regards,
Christian

**Comment by aabashkin** [comment]
@h3xstream Ah, thanks for the explanation I probably should dug into the code a bit more first :)

GenericInputParserHandler is a custom handler that I use in my test cases. It just extends the Default Handler.

I think it makes sense currently the way you've explained it, don't think it is a false positive.

@cschneider4711 

Thanks for the useful info. External parameter entities are indeed an issue.

Regarding DTDs, you are right, and SSRF is a very serious issue on its own. Do you folks think we should create a separate SSRF rule strictly for DTDs?


My test bed is here btw: https://github.com/aabashkin/web-security-testbed

**Comment by h3xstream** [comment]
@aabashkin Let me know if you have other thought or suggestion. (I will close the issue for now)
