### ISSUE TITLE
New Rule : Detect Spring Eval JSP taglib

### ISSUE THREAD

**Issue by aabashkin** [h3xstream/find-sec-bugs#55]
Hi folks,

In regards to http://h3xstream.github.io/find-sec-bugs/bugs.htm#SPEL_INJECTION I think there is an update needed:

```html
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<html lang="en">

<body>
	Spring Expression Language Injection Test - Eval
	<spring:eval expression="${param.input}" />
</body>

</html>
```

Here is the git:

https://github.com/aabashkin/web-security-testbed/blob/master/src/main/webapp/WEB-INF/views/spring-eval.jsp

http://localhost:8080/websecuritytestbed/code-injection/spring-eval?input=T%28java.lang.Runtime%29.getRuntime%28%29.exec%28%22cmd.exe%22%29.toString%28%29

**Comment by h3xstream** [comment]
I have done some testing just to confirm vulnerable samples:

**Vulnerables:**
```xml
<spring:eval expression="${param.input}" var="result" />
```
```xml
<spring:eval expression="${expression}" var="result" /> <!-- assuming the attribute has a tainted source -->
```
```xml
<spring:eval expression=" '${param.value}' == 'test' " var="result" />
```
**Safe:**
```xml
<spring:eval expression="param.value" var="result" />
```

My conclusion is that we can only consider safe the value that follow the regex `[\w\.]+`

**Comment by h3xstream** [comment]
@aabashkin 

The vulnerable / safe samples come from the tests I made.
I conclude that the attribute are resolved first and then pass to the taglib.

-------------
This mean that the jsp code 

`<spring:eval expression="param.value" var="result" />`

can be translate to:
```java
//Not actual code generated
taglib.setExpression(param.value);
```

----------------

`<spring:eval expression="${param.value}" var="result" />`

can be translate to:
```java
//Not actual code generated
String expr = resolve("param.value");
taglib.setExpression(expr);
```
