### ISSUE TITLE
Issue with AES / CBC error detection - STATIC IV implementation

### ISSUE THREAD

**Issue by anagrys** [h3xstream/find-sec-bugs#61]
In Java.
When I initialize a cipher for AES / CBC I get a STATIC IV error.

For encryption: I get this error even if the initialization vector is initialized from a SecureRandom object, provided the initialization is done in a dedicated method. Example of code:

    private final SecureRandom  random                     = new SecureRandom();

    protected byte[] generateInitVector(int length) {
        byte[] array = new byte[length];
        random.nextBytes(array);
        return array;
    }

    public String encrypt(String key, String clearText) throws MyException {
        try {
            // Code to generate the SecretKey from the key
            SecretKey secKey = ...;

            Security.addProvider(new BouncyCastleProvider());

            byte[] iv = generateInitVector(int length);
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS7Padding");
            cipher.init(Cipher.ENCRYPT_MODE, key, new IvParameterSpec(iv));
    [... do stuff]
         }
    }

I have no error raised if I replace:
            byte[] iv = generateInitVector(int length);
with:
        byte[] iv = new byte[16];
        random.nextBytes(iv);

==> this error is not really pretty, but not critical.

There is another case where this error is reported, and in this case it should not be: when instanciating a cipher in DECRYPT_MODE. In that case the IV must be the one which was used to encrypt the message, so by definition it cannot be random.

So: the expected behavior for this check is:
> when the cipher is initialised in DECRYPT mode: the error must not be reported (unless my understanding of the process is wrong, which may still be possible...)
> when the cipher is initialised in ENCRYPT mode: if possible the detection of random IV initialisation should be improved to let use a dedicated function for that.

**Comment by h3xstream** [comment]
Thanks for the precise example.

From my experience, the false positive could often be eliminate with analyse scoped to the **method only**.
Analyzing other method adds extra work to the analyzer and it bring the ambiguity : does the method is overriding in the instance used at runtime?

Would it be ok to only consider `final` method ?

**Comment by h3xstream** [comment]
This issue is happening at the moment where I am looking to do changes on this same detector #62 :)

**Comment by h3xstream** [comment]
This false positive will not be resolve. (won't fix)
At least for now, the analysis will continue to stay scoped to the method only.

The DECRYPT_MODE case was address here -> #64

**Comment by anagrys** [comment]
Thanks, I think the DECRYPT_MODE was truly a bug
For the other case I reckon it can be far more tricky to catch, especially when the method to generate the random number can be hidden anywhere in the call stack...
