### ISSUE TITLE
The IV generation should only be verified for the encryption mode

### ISSUE THREAD

**Issue by trajano** [h3xstream/find-sec-bugs#64]
I've created an OpenID RP implementation, and I had this message
> Initialization vector must be regenerated for each message to be encrypted. 
However, I was not planning to use the IV for encryption but decryption.

From 
https://github.com/trajano/openid-connect/blob/master/openid-connect-core/src/main/java/net/trajano/openidconnect/internal/JcaJsonWebTokenCrypto.java#L288

    final IvParameterSpec spec = new IvParameterSpec(initializationVector);
    contentCipher.init(Cipher.DECRYPT_MODE, contentEncryptionKey, spec);

As noted it is on `DECRYPT_MODE`, perhaps there should be a check to prevent a false positive on this parameter.

**Comment by h3xstream** [comment]
Good point. It should not apply to decryption process..
