### ISSUE TITLE
Clarify the informational log message about CustomInjectionSource.properties

### ISSUE THREAD

**Issue by mmoayyed** [h3xstream/find-sec-bugs#65]
When I run findbugs on a maven project, I see the following in the output:

```
[INFO] --- findbugs-maven-plugin:3.0.1:findbugs (findbugs) @ cas-server-webapp-support ---
[INFO] Fork Value is true
     [java] Jul 19, 2015 7:55:33 AM com.h3xstream.findsecbugs.injection.custom.CustomInjectionSource getInjectionSourceProperties
     [java] INFO: com/h3xstream/findsecbugs/injection/custom/CustomInjectionSource.properties not found.
[INFO] Done FindBugs Analysis....
```

Could this perhaps be logged at DEBUG level?

**Comment by h3xstream** [comment]
This is intentionally put on INFO level. #42
This related to [an optional detector](http://h3xstream.github.io/find-sec-bugs/bugs.htm#CUSTOM_INJECTION) that allow the detection of injection for custom/proprietary API. It can be useful for user of this detector to make sure their configuration is loaded.

The fact that you mention some confusion means that we need to clarify the message.

**Comment by mmoayyed** [comment]
Understood. I think the "Not Found" bit threw me off. Possible workaround might be, log a message when the property file is actually found which would indicate to the user that custom API is being used, or change the message to something that reads less like an error message perhaps.

**Comment by ThrawnCA** [comment]
Perhaps something like this:

    com/h3xstream/findsecbugs/injection/custom/CustomInjectionSource.properties not found; disabling custom injection detector
