### ISSUE TITLE
JDBC api coverage

### ISSUE THREAD

**Issue by h3xstream** [h3xstream/find-sec-bugs#73]
Since the taint analysis has been largely improved, we don't have to rely on the built-in rule of FindBugs.

Many false positive could be eliminate this way.

APIs to cover
 - http://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html
 - http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html
 - http://docs.oracle.com/javase/7/docs/api/java/sql/CallableStatement.html
 - http://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html

**Comment by formanek** [comment]
I can add these. Expect a big pull request with many improvements soon :)

**Comment by formanek** [comment]
Or better add them yourself - I still have many different ideas, so we can work in parallel :)

**Comment by h3xstream** [comment]
@formanek Yup I am working on it this week.

**Comment by h3xstream** [comment]
TODO : Description
