### ISSUE TITLE
All Runtime.exec methods should be taint sinks

### ISSUE THREAD

**Issue by formanek** [h3xstream/find-sec-bugs#92]
Only one-parameter `exec` methods are considered to be taint sinks for command injection. Tainted parameters in other methods are not detected, so there are false negatives.

**Comment by xeno6696** [comment]
I agree.  The single argument call is a pure convenience method.  You
should also flag the other signatures.

**Comment by formanek** [comment]
I have added first two arguments for missing methods, because rewriting environment variables could be dangerous. Should I add the third argument (working directory) too? Could calling `exec(safe1, safe2, new File(taintedVariable))` cause a vulnerability? I think this would be dangerous for some commands, but not an injection and probably intended behaviour.

**Comment by h3xstream** [comment]
It would fall in the directory traversal category ?

**Comment by formanek** [comment]
Yes, detector for path traversal should handle it. We should make a new detector using taint analysis (in version 1.4.4?).

**Comment by h3xstream** [comment]
I also think the path traversal detector should be transform into a `TaintDetector`.
It could be made in 1.4.4.
